[config]
color_system = "okhsl"
saturation = 0.4
lightness = 0.5

[[templates]]
path = "/home/noya/.config/matugen/templates/niri.kdl"
output = "/home/noya/.config/niri/colors.kdl"

[[templates]]
path = "/home/noya/.config/matugen/templates/waybar.css"
output = "/home/noya/.config/waybar/colors.css"
