[global]
frame_color = "#ffb2ba"
separator_color = "#9f8c8d"

[urgency_low]
background = "#1a1112"
foreground = "#f0dedf"
frame_color = "#e5bdc0"

[urgency_normal]
background = "#1a1112"
foreground = "#f0dedf"
frame_color = "#ffb2ba"

[urgency_critical]
background = "#ffb4ab"
foreground = "#690005"
frame_color = "#ffb4ab"
