conky.config = {
    out_to_x = false,
    out_to_wayland = true,

    -- Widget incollato al background
    own_window = true,
    own_window_type = 'desktop',
    own_window_class = 'conky',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_colour = '{{colors.surface.default.hex_stripped}}cc',

    draw_borders = false,
    border_width = 0,

    minimum_width = 280,
    maximum_width = 290,
    border_inner_margin = 12,
    border_outer_margin = 0,

    alignment = 'top_right',
    gap_x = 24,
    gap_y = 56,

    update_interval = 1.0,
    double_buffer = true,
    use_xft = true,
    font = 'JetBrainsMono Nerd Font:size=9.5',

    default_color = '{{colors.on_surface.default.hex}}',
    color1 = '{{colors.primary.default.hex}}',
    color2 = '{{colors.secondary.default.hex}}',
    color3 = '{{colors.on_surface_variant.default.hex}}',
}

conky.text = [[
${color1}${font JetBrainsMono Nerd Font:bold:size=11}󰍹 SISTEMA${font}${color}
${voffset 3}${color2} CPU:${color} ${goto 95}$cpu% ${alignr}${color1}${cpubar 5, 110}${color}
${voffset 2}${color2} RAM:${color} ${goto 95}$mem ${alignr}${color1}${membar 5, 110}${color}
${voffset 1}${goto 95}${color3}${font :size=8}($memperc% di $memmax)${font}${color}

${voffset 2}${color1}${font JetBrainsMono Nerd Font:bold:size=11} STORAGE${font}${color}
${voffset 3}${color2}SSD:${color} ${goto 95}${fs_used /} ${alignr}${color1}${fs_bar 5, 110 /}${color}
${voffset 1}${goto 95}${color3}${font :size=8}($fs_used_perc% - Lib: $fs_free)${font}${color}

${voffset 2}${color1}${font JetBrainsMono Nerd Font:bold:size=11}󰒢 RETE${font}${color}
${voffset 3}${color2} IN:${color}  ${goto 95}${downspeed wlan0} ${alignr}${color3}${font :size=8.5}Tot: ${totaldown wlan0}${font}${color}
${voffset 2}${color2} OUT:${color} ${goto 95}${upspeed wlan0} ${alignr}${color3}${font :size=8.5}Tot: ${totalup wlan0}${font}${color}

${voffset 3}${color1}${font JetBrainsMono Nerd Font:bold:size=11}󰄮 TOP CPU${font}${color}
${voffset 2}${color2}${top name 1}${color} ${alignr}${top cpu 1}%
${voffset 1}${color2}${top name 2}${color} ${alignr}${top cpu 2}%
${voffset 1}${color2}${top name 3}${color} ${alignr}${top cpu 3}%
${voffset 1}${color2}${top name 4}${color} ${alignr}${top cpu 4}%
${voffset 1}${color2}${top name 5}${color} ${alignr}${top cpu 5}%

${voffset 3}${color1}${font JetBrainsMono Nerd Font:bold:size=11} TOP RAM${font}${color}
${voffset 2}${color2}${top_mem name 1}${color} ${alignr}${top_mem mem_res 1}
${voffset 1}${color2}${top_mem name 2}${color} ${alignr}${top_mem mem_res 2}
${voffset 1}${color2}${top_mem name 3}${color} ${alignr}${top_mem mem_res 3}
${voffset 1}${color2}${top_mem name 4}${color} ${alignr}${top_mem mem_res 4}
${voffset 1}${color2}${top_mem name 5}${color} ${alignr}${top_mem mem_res 5}

${voffset 5}${color3}${font :size=8.5}󱑎 Uptime: $uptime_short${font}${color}
]]
